### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by acoto** [creativetimofficial/soft-ui-dashboard-pro-django#4]
Can someone help me with this, I have the subscription but I don't know how to install this repo.

![image](https://github.com/user-attachments/assets/b24a2a82-62ed-4dfb-95e6-e6ed0f71a3ac)

Thanks

**Comment by ElieCom** [comment]
What was the answer?

**Comment by inkeros-gtawaf** [comment]
I'm having this issue as well?
Can you please help?
I have the subscription
